### ISSUE TITLE
Definir Identidade da Versão Alfa

### ISSUE THREAD

**Issue by marcodotcastro** [desenvolvendo-me/ticket-event#111]

**Comment by PhilipeeX** [comment]
index:
https://flowbite.com/blocks/application/advanced-tables/
o primeiro dessa lista porém adicionando a classe hover:bg-gray-100

new e edit:
https://flowbite.com/blocks/application/crud-create-forms/

show: 
https://flowbite.com/blocks/application/crud-read-sections/
