### ISSUE TITLE
Integração de Dados do Evento no Certificado

### ISSUE THREAD

**Issue by marcodotcastro** [desenvolvendo-me/ticket-event#187]
Tarefa: Integração de Dados do Evento no Certificado

Nome: Integrar Informações do Evento no Certificado #150
Descrição: A aplicação deve ser capaz de integrar automaticamente dados relevantes do evento, como nome do evento, data e duração, no template de certificado escolhido pelo admin. Isso assegura que cada certificado seja único e personalizado de acordo com o evento específico.
Critério de Aceite: Cada certificado gerado deve conter as informações específicas do evento para o qual foi emitido, garantindo a precisão e relevância dos dados.

Tarefas:
- [x] Adicionar o campo duração no evento
- [x] Usar a duração do evento no certificado

**Comment by Hegnon** [comment]
Foi adicionado o campo "duration" na area manager e admin. Foram adicionados os dados de  "duration" no template do certificado.
