### ISSUE TITLE
Integrar Sistema de Notas com Mecanismo de Sorteio

### ISSUE THREAD

**Issue by marcodotcastro** [desenvolvendo-me/ticket-event#190]
Tarefa: Integrar Sistema de Notas com Mecanismo de Sorteio

Descrição: Desenvolver uma integração entre o sistema de notas dos questionários e o mecanismo de sorteio, garantindo que apenas os estudantes com nota acima de 70% sejam elegíveis para o sorteio.
Critério de Aceite: A funcionalidade deve verificar automaticamente as notas dos questionários dos estudantes e incluir apenas aqueles com nota igual ou superior a 70% na lista de elegíveis para o sorteio.

**Comment by victoroliveira59** [comment]
A funcionalidade já está pronta, foi realizado somente algumas adaptações na issue #192 para atender os requisitos do sorteio.
