### ISSUE TITLE
Adicionar o cadastro de ingresso para o infoprodutor

### ISSUE THREAD

**Issue by marcodotcastro** [desenvolvendo-me/ticket-event#206]
Descrição: Como infoprodutor, desejo cadastrar os ingressos pela área de _manager_ para que os estudantes recebam um link para gerar o ingresso.

- [x] Incluir as opções **Mostrar**, **Editar** e **Deletar** na listagem dos ingressos
- [x] Incluir botão **Novo** ingresso para um estudante
- [x] Implementar a inclusão do ingresso para um estudante
- [x] Implementar a funcionalidade para o botão **Novo** ingresso para um estudante
- [x] Implementar a tela para editar o ingresso cadastrado para o estudante
- [x] Implementar a exclusão do ingresso cadastrado para o estudante
- [x] Implementar as funcionalidades para as opções **Mostrar**, **Editar** e **Deletar** na listagem

**Comment by osksergio** [comment]
Closes #225
