### ISSUE TITLE
Permitir que o sistema envie um email para estudante ao gerar o ingresso

### ISSUE THREAD

**Issue by marcodotcastro** [desenvolvendo-me/ticket-event#210]

**Comment by AngeloSouza1** [comment]
### Descrição
- [x] - Identificou-se a necessidade de implementar a funcionalidade de envio de ingresso por e-mail no momento de geração do ingresso no sistema InfoProdutor (manager/tickets).

- [x] - As alterações serão concentradas na view show (manager/tickets/show).
---
### Etapas para Implementação

- [x] 1. Identificar o momento de geração do ingresso.

- [x] 2. Implementar a lógica na view show para habilitar o link para ingresso.

- [x] 3. Condição de envio de e-mail com base no campo Checkin.

- [x] 4. Criar uma função no controller Tickets para lidar com o envio de e-mail.

- [x] 5. Definir as rotas necessárias.

- [x] 6. Ajustar o link do botão "Enviar E-mail".

- [x] 7. Ajustar o escopo do texto do e-mail.

- [x] 8. Configurar o envio de e-mail para os ambientes de desenvolvimento e produção, nao são necessárias pois utilizamos a gem  **_letter_opener_web_**
---
### Detalhes Adicionais
- O link para o ingresso atualmente não possui funcionalidade e precisa ser corrigido.
- A condição para habilitar o envio de e-mail depende do campo Checkin.
- A configuração do envio de e-mail foi tentada inicialmente com o SendGrid.Net , sem sucesso, e posteriormente configurada com o servidor GMAIL, mas segundo Feedback não faz parte da demanda.
---
### Imagens
#### _Inserção do link para enviar o e-mail para estudante_
![img2](https://github.com/desenvolvendo-me/ticket-event/assets/104176076/0b7f87fb-0c80-4f68-b642-dc7d748df996)
#### _Envio de E-mail_
![img1](https://github.com/desenvolvendo-me/ticket-event/assets/104176076/30f3b2d8-41af-444e-9918-0438de1628e8)
---
#### Testes
- [x] - Testar a funcionalidade,  após as implementações.
---

  <a href="https://github.com/desenvolvendo-me/ticket-event/pull/226">
      <img src="https://img.shields.io/badge/Referência-%20Pull Request: 226-darkblue" alt="Pull Request: 226">
     </a>
